### ISSUE TITLE
Wrong syntax for python code

### ISSUE THREAD

**Issue by IceDynamix** [Eve-ning/Eve-ning.github.io#1]
Python doesn't use curly brackets!

And also doesn't use `for (int i = 0; i < n; i++)` notation, but `for i in range(n)` instead.

https://github.com/Eve-ning/Eve-ning.github.io/blame/master/_posts/2020-02-24-big-o-notation.markdown#L55

**Comment by Eve-ning** [comment]
woopidiwopwop
Ty will fix :+1:
